simulacion:
  duracion_horas: 168
  semilla_aleatoria: 42 # Para reproducibilidad

planta_coyhaique:
  capacidad_tons: 450
  nivel_inicial_tons: 300

flota:
  num_camiones: 2
  capacidad_camion_tons: 20