# Configuración base para simulación de la cadena de suministro de GLP en Aysén
# Basada en datos reales del informe de vulnerabilidad
# SIN RIESGOS - Solo funcionamiento base del sistema

simulacion:
  duracion_dias: 365  # 1 año completo
  semilla_aleatoria: 42

# ===== FUENTES DE SUMINISTRO (S1) =====
fuentes:
  cabo_negro:
    pais: "Chile"
    ubicacion: "Región de Magallanes"
    capacidad_despacho_diaria_tm: 1000  # Ilimitada para escala de Aysén

  neuquen:
    pais: "Argentina"
    ubicacion: "Provincia de Neuquén"
    capacidad_despacho_diaria_tm: 1000  # Ilimitada para escala de Aysén

# ===== HUB CENTRAL COYHAIQUE (D1) =====
hub_coyhaique:
  # Capacidades reales agregadas (Abastible + Gasco + Lipigas)
  capacidad_granel_tm: 431  # 150 + 41 + 240
  capacidad_envasado_tm: 140  # Capacidad de almacenamiento de producto envasado en planta

  # Inventarios iniciales (50% de capacidad)
  inventario_inicial_granel_tm: 215
  inventario_inicial_envasado_tm: 70

  # Información adicional
  operadores: ["Abastible", "Gasco", "Lipigas"]
  autonomia_dias_promedio: 10  # Con inventario actual
  autonomia_dias_pico: 8  # En mes de mayor demanda (agosto)

# ===== RED DE CENTROS DE DISTRIBUCIÓN ENVASADO (D2b) =====
red_cdes:
  capacidad_total_tm: 161.3  # Capacidad agregada de 46 CDEs
  inventario_inicial_tm: 80  # 50% inicial

  # Información adicional
  numero_cdes: 46
  comunas_cubiertas: 7
  comunas_totales_region: 10

# ===== CLIENTES FINALES (D3) =====
clientes_finales:
  # Demanda anual real (datos 2023)
  demanda_anual_granel_tm: 7270  # 48.3% del total
  demanda_anual_envasado_tm: 7791  # 51.7% del total
  demanda_anual_total_tm: 15061

  # Capacidades de almacenamiento
  capacidad_granel_tm: 911  # Tanques instalados en clientes
  capacidad_envasado_hogares_tm: 660  # Inventario atomizado en hogares (aprox)

  # Inventarios iniciales (50%)
  inventario_inicial_granel_tm: 455
  inventario_inicial_envasado_tm: 330

  # Información demográfica
  poblacion_region: 108000
  consumo_per_capita_anual_kg: 139.5  # 15061 TM / 108000 hab

# ===== TRANSPORTE PRIMARIO (S2) =====
transporte_primario:
  # Política de reabastecimiento
  nivel_activacion_tm: 200  # Cuando pedir camiones (46% de capacidad hub)
  nivel_objetivo_tm: 350  # Nivel objetivo a alcanzar (81% de capacidad hub)

  # Configuración de flota
  flota:
    num_camiones: 12  # Valor medio del rango 7-18
    capacidad_tm: 22  # Capacidad estándar de cisterna

    # Tiempos de viaje (ida y vuelta) según estación
    # Rango (min, max) en días
    tiempo_viaje_temporada_calida_dias: [5.5, 6.0]  # Octubre a marzo
    tiempo_viaje_temporada_fria_dias: [5.7, 7.5]   # Abril a septiembre

  # Información adicional
  distancia_aproximada_km: 1400
  punto_ingreso: "Paso Huemules"
  tramo_argentina_km: 1238  # Del total de 1437 km desde Cabo Negro

# ===== DISTRIBUCIÓN REGIONAL (D2) =====
distribucion_regional:
  # Flotas
  num_camiones_granel: 10  # Camiones graneleros
  num_camiones_jaula: 12   # Camiones para cilindros

  # Capacidades promedio
  capacidad_camion_granel_tm: 8  # Promedio del rango 3.5-12 TM
  capacidad_camion_jaula_tm: 5   # Capacidad estimada para cilindros

  # Políticas de reabastecimiento (umbrales)
  umbral_reabasto_granel_pct: 0.3  # Reabastecer cuando < 30%
  umbral_reabasto_envasado_pct: 0.3

  # Tiempos de distribución (información, no usado en simulación base)
  tiempos_distribucion:
    rutas_largas_norte_horas: [48, 72]  # La Junta, Puyuhuapi, Chaitén
    rutas_largas_sur_horas: [48, 72]    # Cochrane, Guadal
    ruta_puerto_aysen_horas: 8
    distribucion_coyhaique_horas: 4  # Diaria

# ===== MÉTRICAS DE CAPACIDAD DEL SISTEMA =====
capacidades_sistema:
  # Almacenamiento total en la cadena (TM)
  hub_granel: 431
  hub_envasado: 140
  red_cdes: 161.3
  clientes_granel: 911
  clientes_envasado_hogares: 660
  total_sistema: 2303.3  # Suma de todos los niveles

  # Autonomía del sistema (días de demanda promedio)
  autonomia_total_dias: 56  # 2303.3 TM / 41.3 TM/día

  # Flota total
  camiones_cisterna_primario: [7, 18]  # Rango variable
  camiones_granel_regional: 10
  camiones_jaula_regional: 12

# ===== ANÁLISIS Y OUTPUTS =====
analisis:
  variables_respuesta:
    - tasa_satisfaccion_demanda
    - dias_con_desabastecimiento
    - quiebres_stock_hub
    - quiebres_stock_cdes
    - nivel_minimo_inventario_hub
    - viajes_transporte_primario
    - volumen_total_transportado

  # Frecuencia de registro de métricas
  frecuencia_log_dias: 30
